#!/bin/bash

chainId=65f69aa3f0350b295381bf02c8a43e6c15c53173928f5b426d3ae34ad82d154d
curl --request GET \
  --header "factom-provider-token: $FACTOM_API_KEY" \
  --header "Content-Type: application/json" \
  --url https://apiplus-api-sandbox-testnet.factom.com/v1/chains/$chainId
